<?php 
return array (
  'site_name' => '微广互动多用户分销系统',
  'site_title' => '微广互动分销平台',
  'site_logo' => 'tpl/Home/pigcms/common/images/logo-pigcms.png',
  'site_url' => 'http://tys.tzwg.net',
  'site_my' => '小小',
  'server_key' => 'b135ba612d3f5a1d2a07f4a72fb253e6',
  'server_topdomain' => 'tzwg.net',
  'connectout' => '',
  'ischeckuser' => 'true',
  'reg_groupid' => '5',
  'reg_validdays' => '30',
  'router_key' => '',
  'ipc' => '京ICP备132456号',
  'site_qq' => '123456',
  'site_mp' => '',
  'baidu_map_api' => '908bb5a05fa5f839dafeb1a957c7ed51',
  'site_email' => '123456@qq.com',
  'keyword' => '关键词',
  'content' => '描述',
  'countsz' => '',
  'copyright' => 'Copyright © 2012-2014 微广互动版权所有',
);